# Generated by Django 3.1.7 on 2021-03-27 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20)),
                ('tamanho', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=1)),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ingrediente')),
            ],
        ),
    ]
