# Generated by Django 3.1.7 on 2021-03-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredientes',
        ),
    ]
