# Generated by Django 3.1.7 on 2021-03-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pizza_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingrediente',
            field=models.ManyToManyField(related_name='ingrediente', to='core.Ingrediente'),
        ),
    ]
