# Generated by Django 3.1.7 on 2021-03-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pizza_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='preco'),
            preserve_default=False,
        ),
    ]
