# Generated by Django 3.1.7 on 2021-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pizza_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='tamanho',
            field=models.CharField(choices=[('p', 'PEQUENA'), ('m', 'MEDIA'), ('g', 'GRANDE')], max_length=7),
        ),
    ]
