# Generated by Django 3.1.7 on 2021-03-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210328_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preco'),
        ),
    ]
